# docker configuration for running a development server
version: "3.6"

services:
  db:
    image: "postgres:13"
    environment:
      POSTGRES_USER: jobsuser
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: jobserver
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  job-server:
    build: .
    command: /app/manage.py runserver 0.0.0.0:8000
    environment:
      - ADMIN_USERS
      - DATABASE_URL=postgres://jobsuser:pass@db:5432/jobserver
      - DEBUG=True
      - ADMIN_USERS=sanaparveen
      - DJANGO_VITE_DEV_MODE=True
      - GITHUB_TOKEN=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
      - SECRET_KEY=${SECRET_KEY:-12345}
      - SOCIAL_AUTH_GITHUB_KEY=a97d0519503c1e7d0efc
      - SOCIAL_AUTH_GITHUB_SECRET=eaf0b26c7c8bede917a25238a6e78c37def20468
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  postgres_data:
